### ISSUE TITLE
Support for custom .env paths does not work.

### ISSUE THREAD

**Issue by cpburrell** [rolodato/dotenv-safe#25]
Custom paths for .env files is not supported by dotenv-safe.

`var dotenv = require('dotenv-safe');

dotenv.load({ path: '../../.env'});`

Will result in an exception being thrown even if the file '../../.env.example' exists.

**Comment by cpburrell** [comment]
Actually, the code in my PR will only work if there IS a custom path - and will break all other cases. I think the code should be something like:

` var sample = options.sample || options.path ? options.path + '.example' : null || '.env.example';`

**Comment by rolodato** [comment]
Hi @cpburrell. In your case you should be passing both `path` and `sample` options to `dotenv.load`. You can see an example of this in the tests: https://github.com/rolodato/dotenv-safe/blob/e3e6cae9bf37e3279e6c67e0e2642c7a8df8f874/test/index.js#L36-L37

I think it's better to be explicit rather than implicit for this behavior. For example, if you pass a `sample` option but not a `path` option, should we search for `.env` relative to `sample`'s directory? IMO it's simpler to keep the current defaults.

I'll leave this issue open for a while in case others want to give their thoughts on it, but for now I won't be making this change since it's not a bug. Let me know what you think. Thanks!
