### ISSUE TITLE
To load data from .env.example as default

### ISSUE THREAD

**Issue by nikolay-govorov** [rolodato/dotenv-safe#30]
It would be convenient to declare the default values in .env.example. This will allow not to duplicate in the field .env and simplify deployment.

**Comment by piranna** [comment]
This would make the fields as optional with the default values set in `.env.example`. Is this the desired behaviour, instead of only notify what are the required ones?

**Comment by piranna** [comment]
> For example, one of the parameters might be the port on which the application is running. Sometimes we need to override it, but it would be cool if port 3000 was the default.

For this kind of things is why I created the [unify-config](https://www.npmjs.com/package/unify-config) module, this way you can set the defaults in the `config` key of the `package.json` file, that's what npm config uses. I'm planning to add support for `dotenv-safe` or a similar behaviour at this moment.

**Comment by nikolay-govorov** [comment]
Yes, I think it is correct if the developer can control the behavior, and include additional default properties. Now I have thought about how it is not clear how to distinguish the default parameter "empty string" from the missing parameter

**Comment by piranna** [comment]
> it is not clear how to distinguish the default parameter "empty string" from the missing parameter

`dotenv-safe` has  flag the enable that.

**Comment by nikolay-govorov** [comment]
Yes, I know, but I don' understand how it will be combined with other default settings.

**Comment by rolodato** [comment]
I'm afraid that adding this feature would be scope creep. This library's main function is to make sure you're not forgetting to define environment variables. Adding default values means that an example suddenly stops being an example, and instead defines the behaviour of your application. I can imagine it would be confusing to switch between projects that use defaults and others that don't, instead of having a single consistent/explicit behaviour everywhere.

In virtually all cases, I've created a `.env` file by copying `.env.example`, so you can define any "default" values there. There's also a problem in cases where you want to add defaults to some variables, and reference examples to others which shouldn't be treated as defaults.

If you really want this, you could use `dotenv.parse` on `.env.example` and get any default values from there.

**Comment by piranna** [comment]
> @nikolay-govorov The [dotenv-extended](https://www.npmjs.com/package/dotenv-extended) package does what you want.

Nice! Seems what I was looking for :-) Good job! :-D
