### ISSUE TITLE
parsing multiple env files & running the checks selectively

### ISSUE THREAD

**Issue by jomel** [rolodato/dotenv-safe#33]
In dotenv you can load multiple env files, by calling .config({}) multiple times with different 'path' parameters.
eg I can do:
```
dotenv.config({ path: '.env'}); // this contains non-sensitive variables shared by all environments & devs
dotenv.config({ path: '.env.local'}); // this contains dev- or environment-speciffic vars
```

With dotenv-safe I can't seem to achieve the same behaviour.

- If I run 
```
dotenv.config({ path: '.env', example: '.env.template' });
dotenv.config({ path: '.env.local', example: '.env.template' });
```
I get errors about template vars missing from .env (since it only contains SOME vars - correctly)

- If I try 
```
dotenv.config({ path: '.env', example: '' });
dotenv.config({ path: '.env.local', example: '.env.template' });
```
It complains env.example doesnt exist

- I can do:
```
let dotenv = require('dotenv');
let dotenvsafe = require('dotenv-safe');

dotenv.config({ path: '.env' });
dotenvsafe.config({ path: '.env.local', example: '.env.template' });
```
But it just feels ugly.

Any advice?

It would be cool if you could do:
```
dotenv.config({ path: '.env', example: null }); // import files as with plain dotenv
dotenv.config({ path: '.env.local', example: null }); // import files as with plain dotenv
dotenv.config({ example: '.env.template' }); // run the check here
```

**Comment by rolodato** [comment]
This is an interesting use case, though I've never found the need to import more than 1 .env file (or worked on any project that needed it). I'm inclined towards the `require('dotenv')` solution, as dotenv is dotenv-safe's only dependency, so there's nothing extra to install. IMO the intent is also clearer, since it's not immediately obvious what `example: null`, `example: undefined` or `example: ''`should do without reading the documentation. It's also possible (although unlikely) that this could happen:

```js
const path = getExamplePath(); // accidentally returns empty string
require('dotenv-safe').config({ example: path });
```

which would skip validation and silence any errors.

Since there's only one file that you need to load with plain dotenv, you could do this:

```js
require('dotenv').config();
const dotenv = require('dotenv-safe');
dotenv.config({ path: 'foo' });
dotenv.config({ path: 'bar' });
```

I agree it's not as pretty as the other solution, but the intent seems clearer, there's less risk of mistakes, and you add the same amount of variables to the scope. If others run into this issue and it turns out to be a common use case, I'd be happy to rethink this.
